name: ChuckNorrisApp
options:
  bundleIdPrefix: com.tatsunori
  deploymentTarget:
    iOS: 13.0
targets:
  ChuckNorrisApp:
    type: application
    platform: iOS
    sources:
      - path: ChuckNorrisApp
    preBuildScripts:
        - name: Swiftlint
          script: swiftlint
        - name: swiftgen
          script: swiftgen
        - name: sourcery
          script: sourcery
    scheme:
        testTargets:
        - ChuckNorrisAppTests
  ChuckNorrisAppTests:
    type: bundle.unit-test
    deploymentTarget:
        iOS: 13.0
    platform: iOS
    #set the host applications for tests
    dependencies:
        - target: ChuckNorrisApp
    sources:
        - path: ChuckNorrisAppTests
